### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ubani**
added an example to get a quick introduction overview, minor type fixes

### CODE REVIEW

**Comment by Essbante** [comment]
Hi @ubani 

Thank you so much for your contribution and for taking the time to improve our project! I really appreciate your effort in crafting the example around the schema properties

However, after reviewing your submission, I realized that this content might be a bit too detailed for the README. The README primarily serves as a directory of resources, so including in-depth examples there might make it a bit out of place.

What I'd suggest is that we move this discussion to a GitHub issue, where we can rephrase and refine the content together. I think this information would be perfect as an FAQ item or as part of the project wiki, where it can be more thoroughly explained without crowding the main page.

Would you be open to that approach? I’d love to collaborate with you on getting this information to the right place in the project.

Looking forward to your thoughts!

**Comment by essbante-io** [comment]
I just noticed I was logged in with my other GitHub Account. But @Essbante = @essbante-io go figure!

**Comment by ubani** [comment]
@essbante-io this is good as it increases the amount of contributors 😄 

Thank you for your feedback and I see your point. 
I intentionally added this extra detail because if I am a newjoining dev to a topic, an example is what I typically search first for.
What would you think about the option to make this part collapsable?
I updated the file with my suggestion. 
The example could still be moved to the next paragraph or left where it is currently.
Let me know if you still want to move this into a discussion/issue.

**Comment by essbante-io** [comment]
@ubani Thank you for your response and for updating the file with the collapsable section suggestion. I can see where you're coming from.

However, the primary purpose of the README is to provide quick access to project resources, such as links to the documentation, roadmap, communication channels, and so on. This keeps the README concise, making it easier for users to skim through.

We have a dedicated documentation page where the [schemas](https://hyperledger.github.io/identus-docs/tutorials/schemas/create) are explained in more detail. If the current explanation isn't sufficient, I'd recommend raising this as an [issue ](https://github.com/hyperledger/identus-docs/issues) in the docs repository so we can improve the details there.
Additionally, we have a [Quick Start Guide](https://hyperledger.github.io/identus-docs/docs/quick-start/) created for onboarding new developers, which might also serve the purpose you're aiming for with the example.
I'm open to discussing this further, but I think the topic of Schemas is covered in the documentation.

Looking forward to hearing your thoughts on this!

**Comment by ubani** [comment]
@essbante-io thanks, I think the docs are good enough on that matter.

I am moving forward with closing the PR.

**Pull request closed without merging**
